version: 2
models:
  - name: stg_usuarios
    description: "Este modelo limpa e prepara os dados brutos de usuários da camada Bronze."
    columns:
      - name: id_usuario
        description: "Chave primária para identificar unicamente cada usuário."
        tests:
          - unique
          - not_null
  - name: slv_usuarios
    description: "Modelo intermediário que enriquece os dados dos usuários com novas colunas e padronizações."
    columns:
      - name: id_usuario
        description: "Chave primária do usuário."
        tests:
          - unique
          - not_null
      - name: faixa_renda
        description: "Categorização da renda do usuário (Baixa, Média, Alta)."
        tests:
          - accepted_values:
              values: ['Baixa', 'Média', 'Alta', 'N/A']
  - name: gld_contagem_usuarios_cidade
    description: "Tabela analítica final que resume o total de usuários por cidade."
    columns:
      - name: cidade_normalizada
        description: "Nome da cidade."
        tests:
          - not_null
  - name: gld_analise_renda_profissao
    description: "Tabela analítica que resume informações de renda por profissão."
    columns:
      - name: profissao
        description: "Nome da profissão."
        tests:
          - unique
          - not_null
