version: 2

models:
  - name: stg_raw_data__exemplo_vendas
    description: "Staging table for raw sales data. Cleans and prepares data for further transformation."
    columns:
      - name: id_pedido
        description: "Identificador único do pedido."
        tests:
          - unique
          - not_null
      - name: id_cliente
        description: "Identificador único do cliente."
        tests:
          - not_null
      - name: data_venda
        description: "Data em que a venda foi realizada."
        tests:
          - not_null
      - name: produto
        description: "Nome do produto vendido."
      - name: quantidade
        description: "Quantidade do produto vendido."
        tests:
          - not_null
      - name: valor_unitario
        description: "Valor unitário do produto."
        tests:
          - not_null
      - name: valor_total
        description: "Valor total da venda."
        tests:
          - not_null
